---
- block:
  - name: set ip_address
    set_fact:
      ip_address: "{{ ansible_facts[net_interface].ipv4.address }}/{{ ansible_facts[net_interface].ipv4.netmask }}"
      cidr: "{{ ip_address | ipaddr('network/prefix') }}"

  - name: open consul ports
    firewalld:
      port: "{{ item.port }}/{{ item.protocol }}"
      zone: "{{ item.zone }}"
      source: "{{ item.source }}"
      permanent: true
      immediate: true
      state: enabled
    loop:
      - { 'port': '8300', 'protocol': 'tcp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8301', 'protocol': 'tcp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8302', 'protocol': 'tcp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8400', 'protocol': 'tcp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8500', 'protocol': 'tcp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8600', 'protocol': 'tcp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8301', 'protocol': 'udp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8302', 'protocol': 'udp', 'zone': 'public', 'source': "{{ cidr }}" }
      - { 'port': '8600', 'protocol': 'udp', 'zone': 'public', 'source': "{{ cidr }}" }
    tags: firewall

#  - shell: firewall-cmd --zone=public --permanent --add-port={8300,8301,8302,8400,8500,8600}/tcp
#  - shell: firewall-cmd --zone=public --permanent --add-port={8301,8302,8600}/udp
  - command: firewall-cmd --reload
  when: ansible_os_family == 'RedHat'

- set_fact:
    action: "{{ actions[state|default('present')] }}"
  vars:
    actions:
      present: apply
      absent: delete

- block:
  - copy:
      content: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ namespace }}
      dest: /tmp/namespace.yml
      mode: '0644'
      owner: root
      group: root
  - shell: "kubectl {{ action }} -f /tmp/namespace.yml"
  run_once: yes
  when: namespace is not match('^(default|kube-system|kube-public|kube-node-lease)$')
  
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions
- block:
  - copy:
      content: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: consul-probe
          namespace: {{ namespace }}
      dest: /tmp/sa.yml
      mode: '0644'
      owner: root
      group: root
  - shell: "kubectl {{ action }} -f /tmp/sa.yml -n {{ namespace }}"
  run_once: yes

- shell: "kubectl get serviceaccounts consul-probe -n {{ namespace }} -o json | jq -r '.secrets[] | select(.name | match(\"^consul-probe-token-[a-z0-9]+$\") ) | .name '"
  register: s_secret
  run_once: yes
  when: state|default('present') == 'present'
  changed_when: False

- shell: "kubectl get secret {{ s_secret.stdout }} -n {{ namespace }} -o json | jq -r '.data.token' | base64 -d"
  register: s_token
  run_once: yes
  when: state|default('present') == 'present'
  changed_when: False

- set_fact:
    token: "{{ s_token.stdout }}"
  run_once: yes
  when: state|default('present') == 'present'

- block:
  - copy:
      content: |
        apiVersion: rbac.authorization.k8s.io/v1beta1
        kind: ClusterRole
        metadata:
          name: healthcheck-api
          namespace: {{ namespace }}
        rules:
        - nonResourceURLs:
          - '/healthz'
          verbs:
          - 'get'
      dest: /tmp/cr.yml
      mode: '0644'
      owner: root
      group: root
  - shell: "kubectl {{ action }} -f /tmp/cr.yml -n {{ namespace }}"
  run_once: yes

- block:
  - copy:
      content: |
        apiVersion: rbac.authorization.k8s.io/v1beta1
        kind: ClusterRoleBinding
        metadata:
          name: healthcheck-api_consul-probe
          namespace: {{ namespace }}
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: healthcheck-api
        subjects:
        - kind: ServiceAccount
          name: consul-probe
          namespace: {{ namespace }}
      dest: /tmp/crb.yml
      mode: '0644'
      owner: root
      group: root
  - shell: "kubectl {{ action }} -f /tmp/crb.yml -n {{ namespace }}"
  run_once: yes
