- hosts: all
  any_errors_fatal: yes
  become: yes
  become_user: root
  roles:
  - tools

- hosts: k3sm
  gather_facts: yes
  become: yes
  become_user: root
  serial: 1
  #vars:
  #  k3s_cluster_secret: Yourk3sClusterSecret     # USE ANSIBLE EXTRA-VARS
  roles:
  - k3s

# preserves this order in order to obtain all facts (required for generates consul config.json file)
- hosts: k3sm
  gather_facts: yes
  become: yes
  become_user: root
  pre_tasks:
  - import_tasks: roles/consul/tasks/consul-kube.yml
    vars:
      namespace: consul
      state: present
  roles:
  - role: consul
    vars:
      namespace: consul # consul or kube-system
      bootstrap_expect: "{% if ansible_play_hosts | length > 1 %}{{ ansible_play_hosts | length - 1}}{% else %}1{% endif %}"
      datacenter: mydc
      domain: consul
      enable_syslog: !!str false
      #consul_securepass: YourConsulSecurePasswd==  # USE ANSIBLE EXTRA-VARS
      ui: !!str false
      services:
      - service:
          name: k3s
          tags:
          - kubernetes API Server
          port: 6443
          check:
            http: 'https://localhost:6443/healthz'
            tls_skip_verify: true
            method: GET
            header:
              Authorization:
              - "Bearer {{ token }}"
            interval: 5s
            timeout: 1s
