- hosts: k3sm
  gather_facts: yes
  become: yes
  become_user: root
  serial: 1
  vars:
    state: present
    purge: False
    k3s_cluster_secret: Yourk3sClusterSecret
    install_k3s_skip_download: !!str no
  pre_tasks:
  - block:
    - name: install aptitude
      package: name=aptitude force_apt_get=yes
    - name: install packages
      package: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      loop:
        - python-pip
        - python3-pip
        - jq
        - curl
        - open-iscsi
    when: ansible_os_family == 'Debian'
  - name: install python packages
    pip: name={{ item.name }} executable={{ item.executable }}
    loop:
      - { name: 'openshift', executable: 'pip' }
      - { name: 'openshift', executable: 'pip3' }
  roles:
  - role: consul
    when: state == 'absent'
  - k3s

# preserves this order in order to obtain all facts (required for generates consul config.json file)
- hosts: k3sm
  gather_facts: yes
  become: yes
  become_user: root
  pre_tasks:
  - import_tasks: roles/consul/tasks/consul-kube.yml
    vars:
      namespace: consul
      state: present
  roles:
  - role: consul
    when: state == 'present'
    vars:
      namespace: consul # consul or kube-system
      bootstrap_expect: "{% if ansible_play_hosts | length > 1 %}{{ ansible_play_hosts | length - 1}}{% else %}1{% endif %}"
      datacenter: mydc
      domain: consul
      enable_syslog: !!str false
      #securepass: YourConsulSecurePasswd==
      ui: !!str false
      state: present  # present or absent
      services:
      - service:
          name: k8s
          tags:
          - kubernetes API Server
          port: 6443
          check:
            http: 'https://localhost:6443/healthz'
            tls_skip_verify: true
            method: GET
            header:
              Authorization:
              - "Bearer {{ token }}"
            interval: 5s
            timeout: 1s
