---
- block:
  - name: install aptitude
    package: name=aptitude force_apt_get=yes
  - name: install packages
    package: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    loop:
      - python-setuptools
      - python-pip
      - python3-pip
      - jq
      - curl
      - open-iscsi
      #- snapd
  - name: install python packages
    pip: name={{ item.name }} executable={{ item.executable }} state={{ item.state | default('present') }}
    loop:
      - { name: 'openshift', executable: 'pip' }
      - { name: 'requests', executable: 'pip3', state: 'latest'  }
  - command: pip install --upgrade requests
  when: ansible_os_family == 'Debian'

- block:
  - name: install packages
    package: name={{ item }} state=present update_cache=yes
    loop:
      - python-setuptools
      - python3-pip
    #  - jq
      - curl
      #  - open-iscsi
      - epel-release
      - yum-plugin-copr
      - nc
  - name: yum copr enable -y ngompa/snapcore-el7
    command: yum copr enable -y ngompa/snapcore-el7
#  - name: Add ngompa/snapcore-el7
#    yum_repository:
#      name: copr:copr.fedorainfracloud.org:ngompa:snapcore-el7
#      description: Copr repo for snapcore-el7 owned by ngompa
#      file: _copr_ngompa-snapcore-el7
#      baseurl: https://copr-be.cloud.fedoraproject.org/results/ngompa/snapcore-el7/epel-7-$basearch/
#      skip_if_unavailable: yes
#      gpgcheck: yes
#      repo_gpgcheck: no
#      enabled: yes
#      gpgkey: https://copr-be.cloud.fedoraproject.org/results/ngompa/snapcore-el7/pubkey.gpg
  - name: install curl
    yum: name=curl state=present
  - name: install snapd
    package: name=snapd state=present update_cache=yes
  - name: systemctl enable --now snapd.socket
    command: systemctl enable --now snapd.socket
  #- service: name=snapd.socket enabled=yes
  - name: install python packages
    pip: name={{ item.name }} executable={{ item.executable }} state={{ item.state | default('present') }}
    loop:
      - { name: 'openshift', executable: 'pip3' }
      - { name: 'requests', executable: 'pip3', state: 'latest'  }
  - name: snap install jq
    snap:
      name: jq
  when: ansible_os_family == 'RedHat'

- name: snap install lxd
  snap:
    name: lxd