---
- block:
  - name: install aptitude
    package: name=aptitude force_apt_get=yes
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
  - name: install packages
    package: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
    loop:
      - python-setuptools
      - python-pip
      - python3-pip
      - jq
      - curl
      - open-iscsi
      #- snapd
  - name: install python packages
    pip: name={{ item.name }} executable={{ item.executable }} state={{ item.state | default('present') }}
    loop:
      - { name: 'openshift', executable: 'pip' }
      - { name: 'requests', executable: 'pip3', state: 'latest'  }
  - command: pip install --upgrade requests
  when: ansible_os_family == 'Debian'

# yum install yum-plugin-copr epel-release
# yum copr enable ngompa/snapcore-el7
# yum install snapd
# systemctl enable --now snapd.socket

- block:
  - name: install packages
    package: name={{ item }} state=present update_cache=yes
    loop:
      - python-setuptools
      - python2-pip
      - python2-ruamel-yaml
      - unzip
      - python3-pip
    #  - jq
      - curl
      #  - open-iscsi
      - epel-release
      - yum-plugin-copr
      - nc
  - name: yum copr enable -y ngompa/snapcore-el7
    command: yum copr enable -y ngompa/snapcore-el7
#  - name: Add ngompa/snapcore-el7
#    yum_repository:
#      name: copr:copr.fedorainfracloud.org:ngompa:snapcore-el7
#      description: Copr repo for snapcore-el7 owned by ngompa
#      file: _copr_ngompa-snapcore-el7
#      baseurl: https://copr-be.cloud.fedoraproject.org/results/ngompa/snapcore-el7/epel-7-$basearch/
#      skip_if_unavailable: yes
#      gpgcheck: yes
#      repo_gpgcheck: no
#      enabled: yes
#      gpgkey: https://copr-be.cloud.fedoraproject.org/results/ngompa/snapcore-el7/pubkey.gpg
  - name: install curl
    yum: name=curl state=present
  - name: install snapd
    package: name=snapd state=present update_cache=yes
  - name: systemctl enable --now snapd.socket
    command: systemctl enable --now snapd.socket
  #- service: name=snapd.socket enabled=yes
  - name: install python packages
    pip: name={{ item.name }} executable={{ item.executable }} state={{ item.state | default('present') }}
    loop:
#      - { name: 'requests', executable: 'pip', state: 'latest'  }
#      - { name: 'setuptools', executable: 'pip', state: 'latest'  }
#      - { name: 'openshift', executable: 'pip' }
      - { name: 'openshift', executable: 'pip3' }
      - { name: 'requests', executable: 'pip3', state: 'latest'  }
  - command: pip install requests --ignore-installed
  - command: yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - command: yum install jq -y
  when: ansible_os_family == 'RedHat'

# - name: snap install lxd
#   snap:
#     name: lxd